name: MIE_Converter
main: FaigerSYS\MIE_Converter\MIE_Converter
version: "1.0.5"
api: ["4.0.0"]
load: POSTWORLD
author: FaigerSYS
description: "Addon for MapImageEngine to convert images to .mie format"

commands:
  mieconvert:
    description: "Convert image to .mie format"
    permission: "mapimageengine.convert"

permissions:
  mapimageengine.convert:
    default: op
    description: "Allows command usage (/mieconvert)"
